### ISSUE TITLE
Reconnect and pipelining

### ISSUE THREAD

**Issue by vsespb** [PerlRedis/perl-redis#101]
Here is a note in source code:
https://metacpan.org/source/DAMS/Redis-1.976/lib/Redis.pm#L586
```
  # Suppose we have at least one command response pending, but we're about
  # to reconnect.  The new connection will never get a response to any of
  # the pending commands, so delete all those pending responses now.
```

problem is:

1) It's not documented in POD, while it should. It's pretty important imho.

2) Good that it's not documented - means it can be changed. I think it's better to send error to command's callback, or to have option to throw and exception when there was a pending pipelined command during reconnect (like with transactions)

**Comment by dams** [comment]
I've redone the fix, introducing a safe_reconnect option. Let me know what you think.
