### ISSUE TITLE
Redis cluster support

### ISSUE THREAD

**Issue by vsespb** [PerlRedis/perl-redis#109]
Hello.

I see there is a repository for cluster support https://github.com/PerlRedis/perl-redis-cluster

Would you guys share your plans when it can be implemented? Will it be a separated library or a part of CPAN 'Redis' dist?

We're thinking about migrating to cluster soon.

**Comment by dams** [comment]
Hi,

I plan to add support for Redis Cluster. It'll probably be under the Redis::Cluster namespace, but a different dist, and ideally the Redis client backend could be choosed. I have no ETA for this, and if you want to help, I'd be happy to work together on it. Especially setting up proper testing environment is kind of difficult.

**Comment by dams** [comment]
see https://metacpan.org/pod/Redis::Cluster
