### ISSUE TITLE
01-basic.t fails on Solaris

### ISSUE THREAD

**Issue by campbsb** [PerlRedis/perl-redis#110]
Test 01-basic.t hangs on Solaris.
When ignoring the test and using the module anyway, I get error message
Can't use an undefined value as a HASH reference at site_perl/IO/Socket/Timeout.pm line 80
This is on Redis Version 1.978 and was introduced in 1.967 (all tests pass in 1.966)

# perl -V
Summary of my perl5 (revision 5 version 10 subversion 1) configuration:
  Commit id: f49f26c46eb30e17edc39f23c060b8294c44115b
  Platform:
    osname=solaris, osvers=2.10, archname=sun4-solaris-thread-multi
    uname='sunos unstable10s 5.10 generic_142909-17 sun4v sparc sunw,sparc-enterprise-t5220'
    config_args=''
    hint=recommended, useposix=true, d_sigaction=define
    useithreads=define, usemultiplicity=define
    useperlio=define, d_sfio=undef, uselargefiles=define, usesocks=undef
    use64bitint=undef, use64bitall=undef, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='/opt/SUNWspro/bin/cc', ccflags ='-D_REENTRANT -xO3 -m32 -xarch=sparc -I/opt/csw/bdb48/include -I/opt/csw/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DPERL_USE_SAFE_PUTENV',
    optimize='-xO3 -m32 -xarch=sparc',
    cppflags='-D_REENTRANT -xO3 -m32 -xarch=sparc -I/opt/csw/bdb48/include -I/opt/csw/include'
    ccversion='Sun C 5.9 SunOS_sparc Patch 124867-16 2010/08/11', gccversion='', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=4321
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='/opt/SUNWspro/bin/cc', ldflags ='-m32 -xarch=sparc -L/opt/csw/lib -lperl -L/opt/csw/bdb48/lib -L/opt/csw/lib -L/usr/lib -L/usr/ccs/lib -L/lib'
    libpth=/usr/lib /usr/ccs/lib /lib /opt/csw/lib
    libs=-lsocket -lnsl -lgdbm -ldb-4.8 -ldl -lm -lpthread -lc -lperl
    perllibs=-lsocket -lnsl -ldb-4.8 -ldl -lm -lpthread -lc -lperl
    libc=/lib/libc.so, so=so, useshrplib=true, libperl=libperl.so.5.10.1
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-R /opt/csw/lib'
    cccdlflags='-KPIC', lddlflags='-G -L/opt/csw/lib -L/opt/csw/bdb48/lib -L/usr/lib -L/usr/ccs/lib -L/lib'

**Comment by dams** [comment]
This bug should be fixed in IO::Socket::Timeout 0.28 ( just released on CPAN). Can you test and let me know if it fixes your issue ? Thanks

**Comment by campbsb** [comment]
Hi Damien,

Thanks for the swift response. It's now passing on t/01-basic.t, but
failing on t/02-responses.t

t/00-compile.t ............ ok
t/01-basic.t .............. ok
t/02-responses.t .......... 1/? failed to get file descriptor for
filehandle at /opt/csw/share/perl/site_perl/IO/Socket/Timeout.pm line 78.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 29 just after 1.
t/02-responses.t .......... Dubious, test returned 29 (wstat 7424, 0x1d00)
All 1 subtests passed

$ perl t/02-responses.t
ok 1 - connected to our test redis-server
failed to get file descriptor for filehandle at
/opt/csw/share/perl/site_perl/IO/Socket/Timeout.pm line 78.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 29 just after 1.
$

Same setup as before Perl 5.10.1 on Solaris, tested on both sparc & i386.

Steve

**Comment by dams** [comment]
Can you try with 0.29 ( just released on CPAN), which  depends on PerlIO::via::Timeout 0.30, and let me know ? I'm pretty sure it should fix the issue - this time... Thanks

**Comment by campbsb** [comment]
Hi Damien,

That works! The latest Redis package now tests OK on Solaris Perl 5.10.1
for both Sparc & i386 architectures

Thanks,
Steve

**Comment by dams** [comment]
Thanks, I'll release a new version of Redis.pm then.

**Comment by dams** [comment]
fixed in 1.979
