### ISSUE TITLE
Unexpected error condition 54/freebsd

### ISSUE THREAD

**Issue by eserte** [PerlRedis/perl-redis#115]
While testing Redis-1.980 on a freebsd 10.1 system with perl 5.22.0 (and German locale in effect):
```
    # Sleeping 11 seconds, waiting for Redis to timeout...
    
    #   Failed test 'Eventually it gives up and dies'
    #   at t/07-reconnect.t line 122.
    #                   'Unexpected error condition 54/freebsd, please report this as a bug at /home/cpansand/.cpan/build/2015082821/Redis-1.980-rukSOE/blib/lib/Redis.pm line 267.
    # '
    #     doesn't match '(?^:Could not connect to Redis server at)'
    
    #   Failed test '... minimum value for the reconnect reached'
    #   at t/07-reconnect.t line 125.
    # Looks like you failed 2 tests of 3.

#   Failed test 'Reconnect gives up after timeout'
#   at t/07-reconnect.t line 126.
# Looks like you failed 1 test of 12.
t/07-reconnect.t .......... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/12 subtests 
```

**Comment by Kharec** [comment]
Try to put a timeout in your redis conf at line 74. I get that with a timeout to 9 : 

t/01-basic.t ............. ok     
t/02-responses.t ......... ok    
t/03-pubsub.t ............ 2/?     # child is ready to test, signal parent to kill our server
    # parent killed pub/sub redis server, signal child to proceed
    # parent waiting for child 29806...
    # now, check wait_for_messages(), should die...
t/03-pubsub.t ............ 3/?     # CHILD: reconnected (with a 10s timeout)
    # CHILD: is ready to test, signal parent to restart our server
    # PARENT: killed pub/sub redis server, signal child to proceed
    # CHILD: launch wait_for_messages(2), with reconnect...
    # CHILD: reconnected (with a 10s timeout)
    # PARENT: has relaunched the server...
    # CHILD: after 2 sec, nothing yet, retrying
    # CHILD: launch wait_for_messages(2), with reconnect...
    # CHILD: after 2 sec, nothing yet, retrying
    # CHILD: launch wait_for_messages(2), with reconnect...
    # PARENT: waiting for child 29810...
    # CHILD: child received the message
t/03-pubsub.t ............ ok   
t/04-pipeline.t .......... ok    
t/05-nonblock.t .......... ok   
t/06-on-connect.t ........ ok   
t/07-reconnect.t ......... 1/?     # Sleeping 11 seconds, waiting for Redis to timeout...
t/07-reconnect.t ......... ok
