### ISSUE TITLE
Error case that may need to be handled by reconnecting. Seeing mismatched responses.

### ISSUE THREAD

**Issue by ojotoxy** [PerlRedis/perl-redis#116]
If a read timeout occurs, it seems like data will be left in the socket buffer.
If the read timeout error is caught, and more commands are executed on the current redis connection, it seems to me like the old data left in the socket buffer could cause responses to commands to become mismatched from requests.

Does this make sense?
Seems to me like anytime a read timeout occurs the only safe thing to do is reconnect.

**Comment by dams** [comment]
What you say is correct, "anytime a read timeout occurs the only safe thing to do is reconnect". The module should behave like this. Is it not the case when you test it ?

**Comment by ojotoxy** [comment]
I dug a little deeper into this...
I am seeing impossible responses to Redis commands. ('OK' being returned by DEL)
Made me think it's due to mismatched responses or something being left in the buffer.
It turns out the mismatch isn't caused by a timeout, it's some other type of error...
The odd responses start after a redis error:
Error while reading from Redis server: Resource temporarily unavailable at /usr/local/share/perl5/Redis.pm line 267
Which I catch in try::tiny, and continue to use the same Redis.pm handle.

I will probably work around this by just reconnecting upon any error...Any insight into what's going on here is appreciated.

Using Redis.pm 1.981, perl v5.10.1, Linux 2.6.32-431.3.1.el6.x86_64

**Comment by shogo82148** [comment]
I found same problem and wrote a test.
https://github.com/shogo82148/perl-redis/blob/57a2e86b386254ee2a81e1269e3c56aefb3b901d/t/11-timeout.t#L65
It fails in my environment (Redis.pm 1.981, perl v5.18.2, Linux)

```
t/11-timeout.t .. 
    # Subtest: server replies quickly enough
    ok 1
    ok 2
    1..2
ok 1 - server replies quickly enough
    # Subtest: server doesn't replies quickly enough
    ok 1
    ok 2 - the code died as expected
    1..2
ok 2 - server doesn't replies quickly enough
    # Subtest: server doesn't respond at connection (cnx_timeout)
    ok 1 # skip This subtest is failing on some platforms
    ok 2 # skip This subtest is failing on some platforms
    ok 3 # skip This subtest is failing on some platforms
    ok 4 # skip This subtest is failing on some platforms
    1..4
ok 3 - server doesn't respond at connection (cnx_timeout)
    # Subtest: Reconnection by read timeout discards pending commands
    ok 1 - connected to our test redis-server
    ok 2 - set foo bar
    ok 3 - sleep command is timeout
    # waiting for sleep command
    not ok 4 - the value of key foo is bar
    
    #   Failed test 'the value of key foo is bar'
    #   at t/11-timeout.t line 75.
    #          got: 'OK'
    #     expected: 'bar'
    1..4
    # Looks like you failed 1 test of 4.
not ok 4 - Reconnection by read timeout discards pending commands
1..4

#   Failed test 'Reconnection by read timeout discards pending commands'
#   at t/11-timeout.t line 76.
# Looks like you failed 1 test of 4.
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/4 subtests 

Test Summary Report
-------------------
t/11-timeout.t (Wstat: 256 Tests: 4 Failed: 1)
  Failed test:  4
  Non-zero exit status: 1
Files=1, Tests=4,  7 wallclock secs ( 0.03 usr  0.00 sys +  0.23 cusr  0.04 csys =  0.30 CPU)
Result: FAIL
```

**Comment by ojotoxy** [comment]
So, it actually turns out that the error is in fact due to a timeout. The message is just 'Resource temporarily unavailable'.

Here's what I think is going on:
The issue seems to be that __with_reconnect just rethrows the timeout error as it is not of type Redis::X::Reconnect.
If this error is then caught, and the handle is reused, the internal state of the module becomes invalid.
No reconnect attempt is made, and the timed-out response will be read next time.
But $self->{queue} has already had the handler for that response shift'ed off.
Therefore responses become mismatched with queries.

**Comment by ojotoxy** [comment]
Any ideas what a proper fix for this would be? I would be happy to submit a patch but first I would like an agreement on the best way to handle this.

Thanks

**Comment by dams** [comment]
I guess that the right move would be to empty the queue, destroy the socket and then die
