### ISSUE TITLE
[PATCH] spelling mistake

### ISSUE THREAD

**Issue by gregoa** [PerlRedis/perl-redis#118]
In Debian we are currently applying the following patch to Redis.
We thought you might be interested in it too.

    Description: spelling mistake
    Origin: vendor
    Author: gregor herrmann <gregoa@debian.org>
    Last-Update: 2016-02-13
    

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/libredis-perl.git/plain/debian/patches/spelling.patch

Thanks for considering,
  gregor herrmann,
  Debian Perl Group

**Comment by dams** [comment]
Thank you I'll apply it
