### ISSUE TITLE
Redis thread concurency with transactions

### ISSUE THREAD

**Issue by nick2012** [PerlRedis/perl-redis#124]
Why this piece of code wouldn't work in a transactional fashion?
```
$redis_client->multi();    
my $top = get_top_key_from_queue	($redis_client, $queue_src);
my $top_score = get_key_score_from_queue($redis_client, $queue_src, $top);
add_key_to_queue($redis_client, $queue_dst, $top, $top_score);
remove_key_from_queue($redis_client, $queue_src, $top);
$redis_client->exec();
return $top;
```
I had to use a LUA script to do this in a transaction.

**Comment by melo** [comment]
Redis "transactions" are not the same thing as a relational DB transaction.

After multi, you cannot do any "get's", operations after multi do not return data until the exec.

Redis transactions are optimistic. The idea is simple:

* set a watch on all the keys that influence the changes you are about to perform;
* get all the data and transform it locally, without writing to Redis;
* start a multi;
* write your changes to Redis: this operations are actually queued in memory inside Redis, and not applied just now;
* send an exec.

What Redis guarantees is that:
* all writes will happen atomically. It doesn't mean that they will all succeed, but that no other client will be able to change the data while all your "write" commands execute;
* if any of the keys you watched initially were updated by another client, none of the write commands will be applied.

Think of watch as a select for update without the lock. It will track those keys, and will abort the exec (and hence all writes queued between multi and exec) if any of them change.

A multi/exec without watch gains you nothing over pipelined commands, and uses more memory on Redis side.

To learn more see https://redis.io/topics/transactions
