### ISSUE TITLE
Travis CI fails to build my pull-request before even running tests on perls 5.10 and 5.12

### ISSUE THREAD

**Issue by dallaylaen** [PerlRedis/perl-redis#133]
Details are here: 
https://travis-ci.org/PerlRedis/perl-redis/jobs/503968125
https://travis-ci.org/PerlRedis/perl-redis/jobs/503968124

The previous pull-request also failed to build in the same way. Looks like it's a problem with CI setup rather than with the code to be merged.

**Comment by alexandrfox** [comment]
This is fixed by https://github.com/PerlRedis/perl-redis/pull/139
