### ISSUE TITLE
Ping does not raise exception when authentication is required but the connection doesn't authenticate

### ISSUE THREAD

**Issue by willpoorman** [PerlRedis/perl-redis#134]
If a Redis server has `requirepass` enabled, but the redis connection established with this library doesn't set a password, most commands, when you run them, will throw a `NOAUTH Authentication required.`. But if you do this with `$redis->ping()`, it doesn't do so. It doesn't succeed either though. It just returns nothing and keeps going.

Not sure if this intended or not, but it definitely threw me off since all other commands seem to die with the NOAUTH exception and when you run ping in the `redis-cli`, it throw the NOAUTH error there.

Reproduction steps:
1. Have a redis server configured with `requirepass <somepassword>`
2. Write a perl script with the following:
   1. bring in this package
   2. set up a connection without giving a password
   3. Run the ping command and store the response
   4. output the response
```perl
use Redis;
$redis = Redis->new(server => 'localhost:6379');
$response = $redis->ping();
print("response = $response\n");
```
3. Run the script and see that it doesn't fail, but the response is empty.

If you set the password correctly, or you turn off requirepass, then it succesfully responds with 'PONG', as exected. If you set the password incorrectly, then you'll get this error `Redis server refused password`

**Comment by willpoorman** [comment]
By the way, for anyone running across this who is using the `ping` command to test out connecting to a Redis server and running a command to see if it yells at you about about auth, you can substitute it with the `echo` command. It's just as small and simple as ping, but does throw a NOAUTH exception when calling it without a password but when auth is required.

**Comment by shogo82148** [comment]
I think this is expected behavior.
`ping` returns whether the connection is active.
If the connection is inactive, `ping` just returns false value instead of dying.

See https://metacpan.org/pod/Redis#ping

```perl
$r->ping || die "no server?";
```

**Comment by willpoorman** [comment]
Hmm, gotcha. I guess my personal issue with it is that it differs from how ping works on the CLI. I can't really compare it to any other language's Redis library since I haven't used them. But since the PING command on CLI throws the NOAUTH / refused password error, it's what I expected to happen with PING in this library too
