### ISSUE TITLE
Shouldn't it auto-reconnect if connecting via a Sentinel?

### ISSUE THREAD

**Issue by hyacin75** [PerlRedis/perl-redis#140]
Hi, sorry, I'm at a total loss here, so I know this isn't an "issue" per-se, but I don't know where else to ask, and scouring the internet for perl information isn't a fruitful as it was 10-20 years ago sadly.

I'm using your wonderful library, thank you, to connect to a Redis server, and I've just upgraded my setup to a three node Sentinel setup.  It was easy enough to convert the script to get the master from Sentinel, which was great, but on failover now it just dies -

`EOF from server at /usr/share/perl5/Redis.pm line 900.`

I can't find any examples anywhere on how to handle this or anything ... I'm surprised it just quits like that and doesn't try to get the new master from the Sentinel.  Any tips, advice, or examples that I was unable to locate in my searching would be greatly appreciated.

**Comment by dams** [comment]
can you show me how you connect ?

**Comment by hyacin75** [comment]
my $r = Redis->new(sentinels => [ '192.168.0.10:26379', '192.168.0.15:26379', '192.168.0.55:26379' ], service => 'mymaster');
$r->auth('passwordgoeshere');

# listen for messages
$r->subscribe( "plm", \&plmproc );

# loop forever
$r->wait_for_messages(5) while( 1 );

**Comment by hyacin75** [comment]
OK, so skimming the docs for something else I saw the reconnect stuff, so I tried -

`my $r = Redis->new(sentinels => [ '192.168.0.10:26379', '192.168.0.15:26379', '192.168.0.55:26379' ], service => 'mymaster', reconnect => 60, every => 1_000_000);`

and then I was getting -
```
[subscribe] NOAUTH Authentication required. at /usr/share/perl5/Redis.pm line 268.
        ...propagated at /usr/share/perl5/Redis.pm line 606.
```
So I read up some more and tried -

`my $r = Redis->new(sentinels => [ '192.168.0.10:26379', '192.168.0.15:26379', '192.168.0.55:26379' ], service => 'mymaster', reconnect => 60, every => 1_000_000, password => 'passwordgoeshere');`

and now I'm getting -

```
Redis server authentication error: Cannot use command 'auth' while in SUBSCRIBE mode,  at /usr/share/perl5/Redis.pm line 627.
 at /usr/share/perl5/Redis.pm line 627.
        ...propagated at /usr/share/perl5/Redis.pm line 606.
```

So progress, but, still not working quite as I'm aiming for.

Sorry, I assumed reconnecting would be default behaviour which is why I didn't go hunting around for a way to explicitly enable it..
