### ISSUE TITLE
Reconnect for MOVED?

### ISSUE THREAD

**Issue by mrmuskrat** [PerlRedis/perl-redis#159]
https://redis.io/docs/reference/cluster-spec/#moved-redirection

Today we ran into an issue where the cluster configuration was updated without notice. The apps using it started reporting errors including "[get] MOVED 5541 10.177.253.70:15000".

The linked docs say that the client can connect to the new IP:port and reissue the query again. Will this behavior ever get added?

**Comment by togro** [comment]
We had  same problem ....  any idea of how fix ?

**Comment by Yenya** [comment]
You might want to use Redis::Cluster::Fast instead for connecting to Redis Cluster.
