### ISSUE TITLE
Doesn't support sentinels password

### ISSUE THREAD

**Issue by liweitianux** [PerlRedis/perl-redis#164]
Hi.

In our setup, the Redis sentinels also requires a password, though it's the **same** as the Redis servers.  And in this case, `Redis->new()` fails.

Example code:
```perl
#!/usr/bin/env perl

use v5.20;
use warnings;
use Redis;

my $r = Redis->new(sentinels => [ '10.213.245.19:26379' ],
                   service => 'mymaster',
                   password => 'xxx')
   or die "ERROR: failed to connect";

$r->quit;
```

Error:
```
[sentinel] NOAUTH Authentication required.,  at r.pl line 7.
```

Expected:
```sh
# redis-cli -h 10.213.245.19 -p 26379
10.213.245.19:26379> sentinel get-master-addr-by-name mymaster
(error) NOAUTH Authentication required.
10.213.245.19:26379> auth xxx
OK
10.213.245.19:26379> sentinel get-master-addr-by-name mymaster
1) "10.213.245.19"
2) "6379"
10.213.245.19:26379>
```

I looked a bit at the code, and the `$self->sentinel` doesn't receive the password to do authentication.
https://github.com/PerlRedis/perl-redis/blob/master/lib/Redis.pm#L108

Thanks; cheers.

**Comment by linuxmail** [comment]
hi @liweitianux,

can it be, that is was solved woth https://github.com/PerlRedis/perl-redis/pull/166 ?

**Comment by dams** [comment]
thanks for this, indeed it should be fixed. Reopen if needed !

**Comment by liweitianux** [comment]
Cool. Thank you.
