### ISSUE TITLE
multi()/exec() + pipelining

### ISSUE THREAD

**Issue by melo** [PerlRedis/perl-redis#17]
After pull request #10, I'm on the fence wrt the API for multi()/exec() in the presence of pipelining.

The first comments about this were made here:

 * https://github.com/melo/perl-redis/pull/10#issuecomment-4437522
 * https://github.com/melo/perl-redis/pull/10#issuecomment-4438347
 * https://github.com/melo/perl-redis/pull/10#issuecomment-4446523

This issue will track the discussion.

**Comment by agimenez** [comment]
I just stumbled upon this, is the warning from https://metacpan.org/pod/Redis#transaction-handling-methods valid?

>Warning: the behaviour of the TRANSACTIONS commands when combined with pipelining is still under discussion, and you should NOT use them at the same time just now.
