### ISSUE TITLE
Test::CPAN::Meta (et al.) are required even if unused

### ISSUE THREAD

**Issue by rjbs** [PerlRedis/perl-redis#92]
These appear in the test requirements:

```
    "Pod::Coverage::TrustPod" => 0,
    "Test::CPAN::Meta" => 0,
```

These aren't actually used for testing during a normal install, as the tests in question skip when not releasing.  I think they should probably only be in develop requirements.

**Comment by karenetheridge** [comment]
fixed again in #125.
